services:
  postgres:
    image: postgres:15
    container_name: bce_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - back_go_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: bce_redis
    ports:
      - "6379:6379"
    volumes:
      - back_go_redis_data:/data
    command: redis-server --appendonly yes

volumes:
  back_go_postgres_data:
    external: true
  back_go_redis_data:
    external: true
